# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 29 ]  
        target: [ google_apis ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - uses: actions/checkout@v2
    - name: Setup node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install -g appium@v1.20.2
    - run: appium -v
    - run: appium &>/dev/null &
    
    - uses: actions/checkout@v2
  # Download & install the Android SDK.
    - uses: malinskiy/action-android/install-sdk@release/0.1.2
  # Set up platform tools like adb.
    - run: sdkmanager platform-tools
  # Start ADB (and verify that pathing is working correctly).
    - run: adb devices
  # Verify $ANDROID_HOME is properly set for later Gradle commands.
    - run: echo $ANDROID_HOME
    - uses: malinskiy/action-android/emulator-run-cmd@release/0.1.2
      with:
         api: 25
         tag: google_apis
         abi: x86
    - name: Build with Maven
      run: mvn -B package --file pom.xml
   
